export const metadata = {
  title: 'Central Vitual',
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <main className='main-content'>
      <div className='container py-5'>{children}</div>
    </main>
  );
}
